#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
for filename in $DIR/tests/*.py; do
	python "$filename" -v
	echo -e '----------------------------------------' 
done
for filename in $DIR/tests/game_tests/*.py; do
	python $DIR/python/td.py "$filename" -v
	echo -e '----------------------------------------' 
done